---
- name: Setup webserver on Ubuntu machines
  hosts: all
  become: yes
  gather_facts: no
  serial: 1
  vars:
    webserver_port: 80
    webserver_root: "/var/www/html"
    index_location: "index.html"
    server_name: "thunder"
    auth_location: "/etc/nginx/.htpasswd"
    nginx_user: "www-data"

  # Add pre and post tasks to send announcements to a Slack channel
  # helps with operation visibility
  pre_tasks:
    - name: Who is running the update
      become: false
      local_action: command whoami
      register: whoami
    - name: Announce start to slack
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        body: '{"text":"[ansible][{{inventory_hostname}}] {{whoami.stdout}} running setup webserver on a Ubuntu machine :rocket: "}'
        status_code: 200
        body_format: json
      delegate_to: localhost
      become: false

  post_tasks:
    - name: Announce finish to slack
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        body: '{"text":"[ansible][{{inventory_hostname}}] {{whoami.stdout}} completed webserver setup on a Ubuntu machine :thumbsup: "}'
        status_code: 200
        body_format: json
      delegate_to: localhost
      become: false

  roles:
    - install_docker
    - install_nginx
    - cron
    - users
