# Based on https://docs.docker.com/engine/install/ubuntu/

- name: Install Prerequisites
  apt:
    update_cache: yes
    state: latest
    force_apt_get: yes

- name: Allow apt to use a repo over HTTPS
  apt:
    upgrade: full
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  become: true
  become_user: root
  register: https_result
  failed_when: https_result.failed == "true"
  changed_when: https_result.changed == "true"

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  become_user: root
  register: key
  failed_when: key.failed == "true"
  changed_when: key.changed == "true"

# This needs debugging - it failes with "msg": "E:Malformed entry 1 in list file /etc/apt/sources.list.d/download_docker_com_linux_ubuntu_focal_stable.list (Suite), E:The list of sources could not be read."
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu/focal/stable
    state: present
  become: true
  become_user: root
  register: repo
  failed_when: repo.failed == "true"
  changed_when: repo.changed == "true"

- name: Install docker packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true
  become_user: root
  register: docker
  failed_when: docker.failed == "true"
  changed_when: docker.changed == "true"

# testing pulling an image
- name: Pull default Docker image
  docker_image:
    name: "alpine"
    source: pull
  register: image
  failed_when: image.failed == "true"
  changed_when: image.changed == "true"

